import '../../../../const/strings.dart';

const food_ic_item10 = "${GlobalUrl}images/apps/food/food_ic_item10.jpg";
const food_ic_item1 = "${GlobalUrl}images/apps/food/food_ic_item1.jpg";
const food_ic_item4 = "${GlobalUrl}images/apps/food/food_ic_item4.jpg";
const food_ic_item12 = "${GlobalUrl}images/apps/food/food_ic_item12.jpg";
const food_ic_item15 = "${GlobalUrl}images/apps/food/food_ic_item15.jpg";
const food_ic_item13 = "${GlobalUrl}images/apps/food/food_ic_item13.jpg";
const food_ic_item7 = "${GlobalUrl}images/apps/food/food_ic_item7.jpg";
const food_ic_item6 = "${GlobalUrl}images/apps/food/food_ic_item6.jpg";
const food_ic_item11 = "${GlobalUrl}images/apps/food/food_ic_item11.jpg";
const food_ic_item2 = "${GlobalUrl}images/apps/food/food_ic_item2.jpg";
const food_ic_popular4 = "${GlobalUrl}images/apps/food/food_ic_popular4.jpg";
const food_ic_item14 = "${GlobalUrl}images/apps/food/food_ic_item14.jpg";
const food_ic_intro = "${GlobalUrl}images/apps/food/food_ic_intro.jpg";
const food_ic_popular2 = "${GlobalUrl}images/apps/food/food_ic_popular2.jpg";
const food_ic_popular3 = "${GlobalUrl}images/apps/food/food_ic_popular3.jpg";
const food_ic_popular1 = "${GlobalUrl}images/apps/food/food_ic_popular1.jpg";
const food_ic_walk1 = "${GlobalUrl}images/apps/food/food_ic_walk1.svg";
const food_ic_walk2 = "${GlobalUrl}images/apps/food/food_ic_walk2.svg";
const food_ic_walk3 = "${GlobalUrl}images/apps/food/food_ic_walk3.svg";
const food_dinner_table = "${GlobalUrl}images/apps/food/food_dinner_table.svg";
const food_ic_google_fill =
    "${GlobalUrl}images/apps/food/food_ic_google_fill.svg";
const food_ic_fb = "${GlobalUrl}images/apps/food/food_ic_fb.svg";
const food_ic_login = "${GlobalUrl}images/apps/food/food_ic_login.jpg";
const food_ic_user1 = "${GlobalUrl}images/apps/food/food_ic_user1.png";
const food_ic_user2 = "${GlobalUrl}images/apps/food/food_ic_user2.png";
const food_ic_user3 = "${GlobalUrl}images/apps/food/food_ic_user3.png";
const food_ic_user5 = "${GlobalUrl}images/apps/food/food_ic_user5.png";
const food_ic_user4 = "${GlobalUrl}images/apps/food/food_ic_user4.png";
const food_cloche = "${GlobalUrl}images/apps/food/food_cloche.svg";
const food_ic_table = "${GlobalUrl}images/apps/food/food_ic_table.svg";
const food_google_wallet =
    "${GlobalUrl}images/apps/food/food_google_wallet.svg";
const food_whatsapp = "${GlobalUrl}images/apps/food/food_whatsapp.svg";
const food_ic_rbs = "${GlobalUrl}images/apps/food/food_ic_rbs.png";
const food_ic_citi = "${GlobalUrl}images/apps/food/food_ic_citi.png";
const food_ic_hdfc = "${GlobalUrl}images/apps/food/food_ic_hdfc.png";
const food_ic_hsbc = "${GlobalUrl}images/apps/food/food_ic_hsbc.jpg";
const food_ic_america = "${GlobalUrl}images/apps/food/food_ic_america.jpg";
const food_ic_fab_back = "${GlobalUrl}images/apps/food/food_ic_fab_back.png";
const food_ic_comass = "${GlobalUrl}images/apps/food/food_ic_comass.svg";
const food_ic_delivery = "${GlobalUrl}images/apps/food/food_ic_delivery.svg";
const food_c_type = "${GlobalUrl}images/apps/food/food_c_type.png";
const food_ic_map = "${GlobalUrl}images/apps/food/food_ic_map.png";
