name: mohit_ui_collection
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
#  firebase_cached_image: ^0.5.2

#  flutter_cors: ^1.5.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  nb_utils: ^6.0.4
  intl: ^0.18.1
  google_fonts: ^6.1.0


  velocity_x: ^4.1.1
  fluttertoast: ^8.2.2
  pin_code_fields: ^8.0.1

  cached_network_image: ^3.3.0

  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-beta.2

  timeline_tile: ^2.0.0
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.7


  # Common
  share_plus: ^7.0.2
  url_launcher: ^6.1.11
#  http: ^0.13.6
  html: ^0.15.3



  # STATE MANAGEMENT
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  package_info_plus: 4.1.0
  #ui
  flutter_slidable: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  simple_animations: ^5.0.2
  flutter_zoom_drawer: ^3.1.1
  sleek_circular_slider: ^2.0.1
  syncfusion_flutter_charts: ^21.2.6

  flutter_charts: ^0.4.0
  # UI

  flutter_colorpicker: ^1.0.3
  signature: ^5.4.0
  dots_indicator: ^3.0.0
  percent_indicator: ^4.2.3
  animations: ^2.0.7
  lottie: ^2.3.2
  liquid_swipe: ^3.1.0
  showcaseview: ^2.0.3
  fl_chart: ^0.36.1
  flutter_reaction_button: ^2.0.1+2
  smooth_star_rating_null_safety: ^1.0.4+2
  country_calling_code_picker: ^2.0.1
  simple_gradient_text: ^1.2.4
  #maps
  google_maps_flutter: ^2.5.0


  path_drawing: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1

  # VIDEOS
  video_player: ^2.6.1

  # SMART HOME #
  syncfusion_flutter_gauges: ^21.2.6
  dotted_line: ^3.1.0
  country_code_picker: 2.0.2

  # COINPRO
  smooth_page_indicator: ^1.1.0

  # SOCIAL V
  story_view: ^0.14.0

  just_audio: ^0.9.33
  camera: ^0.10.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/placeholder.jpg
#    - assets/images/emptyScreen1/
#    - assets/images/errorScreens/
#    - assets/images/movie/
#    - assets/images/home_banner/
#    - assets/images/product/
#    - assets/images/user/
#    - assets/images/pricingPlans/
#    - assets/images/themes/
#    - assets/images/themes/theme1/
#    - assets/images/themes/theme2/
#    - assets/images/themes/theme3/
#    - assets/images/themes/theme4/
#    - assets/images/themes/theme5/
#    - assets/images/themes/theme6/
#    - assets/images/themes/theme7/
#    - assets/images/themes/theme8/
#    - assets/images/themes/theme9/
#    - assets/images/themes/theme10/
#    - assets/images/themes/theme11/
#    - assets/images/themes/theme12/
#    - assets/images/themes/theme13/
#    - assets/images/themes/theme14/
#    - assets/images/themes/theme15/
#    - assets/images/themes/theme15/walkthrough_images/
#    - assets/images/themes/theme15/pets_screen/
#    - assets/images/themes/theme15/pets_images/
#    - assets/images/themes/theme15/payment_images/
#    - assets/images/themes/theme15/flags/
#    - assets/images/themes/theme15/icons/
#    - assets/images/themes/theme15/dashboard/
#    - assets/images/themes/theme15/account_images/
#    - assets/images/dashboard/
#    - assets/images/dashboard/analytics/
#    - assets/images/dashboard/banking_dashboard/
#    - assets/images/dashboard/health_medical/
#    - assets/images/dashboard/smart_home/
#    - assets/images/dashboard/split_bill/
#    - assets/images/dashboard/utility_tracker/
#    - assets/images/apps/ecommerce/
#    - assets/images/apps/ecommerce/onboarding/
#    - assets/images/apps/food_delivery/
#    - assets/images/apps/social/
#    - assets/images/apps/grocery/
#    - assets/images/apps/orapay/
#    - assets/images/apps/food/
#    - assets/images/apps/shophop/
#    - assets/images/apps/shophop/img/
#    - assets/images/apps/shophop/img/products/
#    - assets/images/apps/shophop/img/products/banners/
#    - assets/images/apps/shophop/img/products/decor/
#    - assets/images/apps/shophop/img/products/dress/
#    - assets/images/apps/shophop/img/products/shoes/
#    - assets/images/apps/quiz/
#    - assets/images/apps/learner/
#    - assets/images/apps/banking/
#    - assets/images/apps/hairSalon/
#    - assets/images/apps/smartDeck/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf

    - family: Andina
      fonts:
        - asset: assets/fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: assets/fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/googlesansebold.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
