import '../../../../../const/strings.dart';

List images = [
  "${GlobalUrl}images/themes/theme15/pets_images/dog1.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog2.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog7.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog8.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog3.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog4.png",
  "${GlobalUrl}images/themes/theme15/dashboard/d2.png",
  "${GlobalUrl}images/themes/theme15/dashboard/d3.png",
  "${GlobalUrl}images/themes/theme15/dashboard/d4.png",
  "${GlobalUrl}images/themes/theme15/dashboard/d5.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog4.png",
  "${GlobalUrl}images/themes/theme15/dashboard/d4.png",
  "${GlobalUrl}images/themes/theme15/dashboard/d2.png",
  "${GlobalUrl}images/themes/theme15/dashboard/d3.png",
  "${GlobalUrl}images/themes/theme15/dashboard/d1.png",
  "${GlobalUrl}images/themes/theme15/dashboard/d7.png",
  "${GlobalUrl}images/themes/theme15/dashboard/d2.png",
];
List dogImages = [
  "${GlobalUrl}images/themes/theme15/pets_images/dog7.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog8.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog3.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog4.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog5.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog6.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog1.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog2.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog3.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog7.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog8.png",
  "${GlobalUrl}images/themes/theme15/pets_images/dog6.png",
];
List catgoriesimages = [
  "${GlobalUrl}images/themes/theme15/pets_images/dog2.png",
  "${GlobalUrl}images/themes/theme15/pets_screen/cat.png",
  "${GlobalUrl}images/themes/theme15/pets_screen/fishimage.png",
  "${GlobalUrl}images/themes/theme15/pets_images/chick_image.png",
  "${GlobalUrl}images/themes/theme15/pets_screen/mouse_image.png",
];
List accountImage = [
  "${GlobalUrl}images/themes/theme15/account_images/profile2.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile3.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile4.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile5.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile2.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile3.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile4.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile5.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile2.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile3.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile4.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile5.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile2.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile3.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile4.png",
  "${GlobalUrl}images/themes/theme15/account_images/profile5.png",
];
